# Line 1: Updated logic for improved handling
# Line 2: Updated logic for improved handling
# Line 3: Updated logic for improved handling
# Line 4: Updated logic for improved handling
# Line 5: Updated logic for improved handling
# Line 6: Updated logic for improved handling
# Line 7: Updated logic for improved handling
# Line 8: Updated logic for improved handling
# Line 9: Updated logic for improved handling
# Line 10: Updated logic for improved handling
# Line 11: Updated logic for improved handling
# Line 12: Updated logic for improved handling
# Line 13: Updated logic for improved handling
# Line 14: Updated logic for improved handling
